version: '3.8'

services:
  spring:
    build: .
    container_name: spring
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env

  ngrok:
    image: wernight/ngrok
    environment:
      - ENVIRONMENT=dev
    volumes:
      - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    ports:
      - "4040:4040"
    networks:
      - app-network
    command: [ "ngrok", "http", "spring:8080", "--log=stdout" ]

networks:
  app-network:
    driver: bridge